```{r}
library(tidyverse)
library(kmer)
library(phangorn)
library(GUniFrac)
library(ggtree)
library(patchwork)
library(bioseq)
library(ape)
library(Biostrings)
```

# Custom functions

```{r}
dna_to_DNAbin <- function (dna){
  DNAbin <- as_DNAbin(dna)
  names(DNAbin) <- names(dna)
  return(DNAbin)
}

read_fasta_df <- function (file = "") {
  fasta <- readLines(file)
  ind <- grep(">", fasta)
  s <- data.frame(ind = ind, from = ind + 1, to = c((ind - 
    1)[-1], length(fasta)))
  seqs <- rep(NA, length(ind))
  for (i in 1:length(ind)) {
    seqs[i] <- paste(fasta[s$from[i]:s$to[i]], collapse = "")
  }
  tib <- tibble(label = gsub(">", "", fasta[ind]), sequence = seqs)
  return(tib)
}
```

# Sequence and Profile tables

```{r}
# Import sequence table
seqs <- read_tsv("Symportal_data/post_med_seqs/186_20211115_03_DBV_20211116T014450.seqs.absolute.abund_and_meta.txt") %>%
    mutate(sample_name = as.factor(sample_name))

full_meta <- seqs %>% select(sample_name) %>%
  mutate(colony = str_sub(sample_name, start = 1, end = 1)) %>%
  filter(!(is.na(sample_name)))

# Convert to long format
seqs_long <- seqs %>%
  filter(!is.na(sample_name)) %>%
  select(sample_name, A5a:`66235_D`) %>%
  pivot_longer(A5a:`66235_D`) %>%
  filter(value > 0) %>% # Remove zero values
  left_join(., full_meta)

# Add relative abundances
seqs_long <- seqs_long %>%
  mutate(name = as.factor(name)) %>%
  group_by(sample_name) %>%
  mutate(value_rel = value/sum(value)) %>% # Convert to relative abundance
  ungroup()

san_check <- seqs_long %>%
  group_by(sample_name) %>%
  summarise(total = sum(value))

# Create a random palette for each sequence
n <- length(levels(seqs_long$name))
seqs_pal = rainbow(n, s=.6, v=.9)[sample(1:n,n, replace = FALSE)]
names(seqs_pal) <- levels(seqs_long$name)

# Read in the profile data
profiles_raw <- read_tsv("Symportal_data/its2_type_profiles/186_20211115_03_DBV_20211116T014450.profiles.absolute.abund_and_meta.txt", skip = 6) %>%
    select(sample_name = `X2`, `C50b-C3-C3vz-C3wa`:`D1-D1u-D4-D1jw`) %>%
    filter(!is.na(sample_name))

profiles_long <- profiles_raw %>%
  pivot_longer(`C50b-C3-C3vz-C3wa`:`D1-D1u-D4-D1jw`) %>% # Convert it to long format
  mutate(name = paste0("p_", name)) %>% # Add a p_ to the beginning of each profile (Some profiles are single sequence profiles and clash with the Sequence names)
  filter(sample_name %in% seqs_long$sample_name) %>% # Remove samples that done appear in the Sequence dataframe
  group_by(sample_name) %>%
  mutate(value = as.numeric(value)) %>%
  filter(value > 0) %>% # Remove 0 abundance profiles
  mutate(sample_name = as.factor(sample_name)) %>% # DONT USE NUMBERS FOR SAMPLE NAMES
  ungroup() %>%
  left_join(., full_meta) # Add in metadata

# What is the total number of profile-related sequences in each sample?
profiles_sum <- profiles_long %>%
  group_by(sample_name) %>%
  summarise(total = sum(value))

# How many sequences in each sample are not part of a profile?
residual <- left_join(profiles_sum, san_check, by = "sample_name") %>%
  mutate(residual = total.y - total.x) %>%
  select(sample_name, value = residual) %>%
  mutate(name = "non-profile sequences") %>%
  left_join(., full_meta)

# Combine the profiles and non-profile sequences
profile_data <- rbind(profiles_long, residual) %>%
  group_by(sample_name) %>%
  mutate(value_rel = value/sum(value)) %>% # convert to relative abundance
  mutate(name = as.factor(name))
  
# Create palette for profiles (this is a darker palette)
n <- length(levels(profile_data$name))
pro_pal <- ggsci::pal_d3(palette = "category10")

profile_pal = pro_pal(n)
names(profile_pal) <- levels(profile_data$name)

# Merge the palettes and replace the non-profile sequences with grey
all_pal <- c(seqs_pal, profile_pal)
all_pal['non-profile sequences'] <- "#000000" 

# Join profiles and sequence data together into single dataframe
all_data <- rbind(seqs_long, profile_data)

# Bit of manual hard-coding of the order of samples based on their profiles
# sample_order <- all_data %>%
#   group_by(sample_name) %>%
#   slice_max(value_rel, with_ties = FALSE) %>%
#   arrange(name)

#
sample_order <- profiles_raw %>%
  select(sample_name) %>%
  left_join(., full_meta)
```

```{r}
summary_C <- seqs_long %>%
    mutate(genus = case_when(str_detect(name, "C|_C") ~ "Cladocopium",
                           str_detect(name, "D|_D") ~ "Durusdinium",
                           str_detect(name, "A|_A") ~ "Symbiodinium",
                           str_detect(name, "B|_B") ~ "Breviolum")) %>%
  group_by(sample_name, genus) %>%
  summarise(value = sum(value)) %>%
  pivot_wider(names_from = genus, values_from = value) %>%
    mutate(across(everything(), replace_na, 0))

write_csv(summary_C, "Symportal_data/summary_genera.csv")
```
# Unifrac distances

```{r}
fasta <- MRNhelp::read_fasta_df("Symportal_data/post_med_seqs/186_20211115_03_DBV_20211116T014450.seqs.fasta") %>%
  filter(label %in% seqs_long$name) %>%
  filter(str_sub(label, 1, 1) != "A",
         !(str_detect(label, "_A")), # Filter Symbiodinium Sequences
        str_sub(label, 1, 1) != "B",
         !(str_detect(label, "_B"))) %>%  # Filter Breviolum Sequences
  deframe() %>%
  as_dna()

kdist <- fasta %>%
  dna_to_DNAbin() %>%
  kdistance(k = 7, residues = "DNA", method = "edgar") %>%
  as.matrix()

tree <- kdist %>% phangorn::upgma()

seqs_wide <- seqs_long %>%
  select(sample_name, name, value) %>%
  filter(str_sub(name, 1, 1) != "A",
         !(str_detect(name, "_A")), # Filter Symbiodinium Sequences
        str_sub(name, 1, 1) != "B",
         !(str_detect(name, "_B"))) %>%  # Filter Breviolum Sequences
  pivot_wider(names_from = name, values_from = value) %>%
  mutate(across(everything(), replace_na, 0)) %>%
  tibble::column_to_rownames(var = "sample_name")

unidist <- GUniFrac(seqs_wide, tree)
unifracs <- unidist$unifracs
du <- unifracs[, , "d_UW"] # d_UW does a good job of discriminating colonies. What discriminates habitats?
hclust_samps <- upgma(du)

ggtree_samps <- ggtree::ggtree(hclust_samps)$data %>%
  filter(isTip == "TRUE") %>%
  arrange(y)

p_tree <- ggtree(hclust_samps, size = 0.2) +
  scale_x_reverse() +
  theme(aspect.ratio = 1)

p_tree$data <- left_join(p_tree$data, full_meta, by = c("label" = "sample_name"))

p_tree + geom_tippoint(aes(colour = colony), size = 2, alpha = 0.3)
```

# Plot

```{r}
# plot_df <- all_data %>%
#   mutate(sample_name = fct_relevel(sample_name, sample_order$sample_name))
# breaks <- colnames(profiles_raw %>% select(-sample_name))
# 
# ggplot(plot_df, aes(value_rel, sample_name)) +
# geom_bar(stat = "identity", aes(fill = name, colour = name)) +
# #facet_wrap(~coral_species, nrow = 1, scales = "free_x") +
# theme(aspect.ratio = 0.5, legend.position = "none", axis.text.y=element_blank(), axis.ticks.y = element_blank(),
#       axis.text.x=element_blank(), axis.ticks.x = element_blank()) +
# scale_fill_manual(values = all_pal, breaks = colnames(profiles_raw %>% select(-sample_name))) +
# scale_colour_manual(values = all_pal, breaks = colnames(profiles_raw %>% select(-sample_name))) +
# geom_vline(xintercept = 1, size = 1) +
# #guides(fill=guide_legend(ncol=3)) +
# ylab("Sample") +
# xlab("ITS2 Profile (left) and Sequence (right) relative abundance")

# Plot IDEA ORDER SAMPLES BY UNIFRAC DISTANCES

plot_df <- all_data %>%
  mutate(sample_name = fct_relevel(sample_name, ggtree_samps$label))

theme_set(theme_bw())

p_bar_uni <- 
ggplot(plot_df, aes(value_rel, sample_name)) +
geom_bar(stat = "identity", aes(fill = name, colour = name)) +
#facet_wrap(~coral_species, nrow = 1, scales = "free_x") +
theme(aspect.ratio = 0.8, legend.position = "left", axis.text.y=element_blank(), axis.ticks.y = element_blank(),
      axis.text.x=element_blank(), axis.ticks.x = element_blank(),
      axis.title.x = element_blank(), axis.title.y = element_blank(),
      panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.ticks = element_blank()) +
scale_fill_manual(values = all_pal, breaks = levels(profile_data$name)) +
scale_colour_manual(values = all_pal, breaks = levels(profile_data$name)) +
geom_vline(xintercept = 1, size = 1) +
guides(fill=guide_legend(ncol=1))
```

```{r}
p_bar_uni + p_tree + geom_tippoint(aes(colour = colony), size = 2, alpha = 0.3)
```



